version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.3
    container_name: rocketmq-namesrv
    ports:
      - "9876:9876"
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m -Xmn128m"
    command: sh mqnamesrv
    healthcheck:
      test: ["CMD", "sh", "-c", "ps -ef | grep java | grep NamesrvStartup | grep -v grep | wc -l | grep -q 1"]
      interval: 15s
      timeout: 10s
      retries: 5

  rocketmq-broker:
    image: apache/rocketmq:5.3.3
    container_name: rocketmq-broker
    depends_on:
      - rocketmq-namesrv
    ports:
      - "10911:10911"
      - "10909:10909"
    environment:
      NAMESRV_ADDR: rocketmq-namesrv:9876
      JAVA_OPT_EXT: "-Xms512m -Xmx512m -Xmn256m"
    volumes:
      - ./broker.conf:/home/rocketmq/rocketmq-5.1.4/conf/broker.conf
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.1.4/conf/broker.conf

  rocketmq-console:
    image: apacherocketmq/rocketmq-dashboard:2.0.1
    container_name: rocketmq-console
    restart: always
    ports:
      - "8088:8080"
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rocketmq-namesrv:9876"
    depends_on:
      - rocketmq-namesrv

volumes:
  mysql_data:
  redis_data: