spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: taskuser
    password: taskpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  # define redis properties here

  redis:
    host: localhost
    port: 6379

rocketmq:
  name-server: localhost:9876
  producer:
    group: notification-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    retry-next-server: true
